# Generated by Django 4.1.3 on 2022-12-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.URLField(default='https://cdn.browshot.com/static/images/not-found.png', max_length=1000),
        ),
    ]
